# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui/qt-imapSession.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SessionDialog(object):
    def setupUi(self, SessionDialog):
        SessionDialog.setObjectName("SessionDialog")
        SessionDialog.resize(748, 653)
        SessionDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SessionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(SessionDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(SessionDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_ClientPeer = QtWidgets.QLineEdit(SessionDialog)
        self.lineEdit_ClientPeer.setEnabled(True)
        self.lineEdit_ClientPeer.setReadOnly(True)
        self.lineEdit_ClientPeer.setObjectName("lineEdit_ClientPeer")
        self.gridLayout.addWidget(self.lineEdit_ClientPeer, 1, 0, 1, 1)
        self.lineEdit_ServerPeer = QtWidgets.QLineEdit(SessionDialog)
        self.lineEdit_ServerPeer.setReadOnly(True)
        self.lineEdit_ServerPeer.setObjectName("lineEdit_ServerPeer")
        self.gridLayout.addWidget(self.lineEdit_ServerPeer, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(SessionDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEdit_CurrentState = QtWidgets.QLineEdit(SessionDialog)
        self.lineEdit_CurrentState.setReadOnly(True)
        self.lineEdit_CurrentState.setObjectName("lineEdit_CurrentState")
        self.gridLayout.addWidget(self.lineEdit_CurrentState, 1, 2, 1, 1)
        self.cb_intercepted = QtWidgets.QCheckBox(SessionDialog)
        self.cb_intercepted.setObjectName("cb_intercepted")
        self.gridLayout.addWidget(self.cb_intercepted, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget_ImapSession = QtWidgets.QTabWidget(SessionDialog)
        self.tabWidget_ImapSession.setObjectName("tabWidget_ImapSession")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView_SessionHistory = QtWidgets.QTableView(self.tab)
        self.tableView_SessionHistory.setObjectName("tableView_SessionHistory")
        self.horizontalLayout.addWidget(self.tableView_SessionHistory)
        self.frame_CommandTuple = QtWidgets.QFrame(self.tab)
        self.frame_CommandTuple.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CommandTuple.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CommandTuple.setObjectName("frame_CommandTuple")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_CommandTuple)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget_Command = QtWidgets.QTabWidget(self.frame_CommandTuple)
        self.tabWidget_Command.setObjectName("tabWidget_Command")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit_CommandRaw = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_CommandRaw.setReadOnly(True)
        self.plainTextEdit_CommandRaw.setObjectName("plainTextEdit_CommandRaw")
        self.verticalLayout_3.addWidget(self.plainTextEdit_CommandRaw)
        self.tabWidget_Command.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget_CommandTree = QtWidgets.QTreeWidget(self.tab_4)
        self.treeWidget_CommandTree.setObjectName("treeWidget_CommandTree")
        self.verticalLayout_2.addWidget(self.treeWidget_CommandTree)
        self.tabWidget_Command.addTab(self.tab_4, "")
        self.verticalLayout_5.addWidget(self.tabWidget_Command)
        self.tabWidget_Response = QtWidgets.QTabWidget(self.frame_CommandTuple)
        self.tabWidget_Response.setObjectName("tabWidget_Response")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit_Reponse_Raw = QtWidgets.QPlainTextEdit(self.tab_5)
        self.plainTextEdit_Reponse_Raw.setReadOnly(True)
        self.plainTextEdit_Reponse_Raw.setObjectName("plainTextEdit_Reponse_Raw")
        self.verticalLayout_4.addWidget(self.plainTextEdit_Reponse_Raw)
        self.tabWidget_Response.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.treeWidget_ResponseTree = QtWidgets.QTreeWidget(self.tab_6)
        self.treeWidget_ResponseTree.setObjectName("treeWidget_ResponseTree")
        self.verticalLayout_6.addWidget(self.treeWidget_ResponseTree)
        self.tabWidget_Response.addTab(self.tab_6, "")
        self.verticalLayout_5.addWidget(self.tabWidget_Response)
        self.horizontalLayout.addWidget(self.frame_CommandTuple)
        self.tabWidget_ImapSession.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.plainTextEdit_NewCommand = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_NewCommand.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_NewCommand.setObjectName("plainTextEdit_NewCommand")
        self.verticalLayout_7.addWidget(self.plainTextEdit_NewCommand)
        self.checkBox_NewCommand_ConvertLF = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_NewCommand_ConvertLF.setChecked(True)
        self.checkBox_NewCommand_ConvertLF.setObjectName("checkBox_NewCommand_ConvertLF")
        self.verticalLayout_7.addWidget(self.checkBox_NewCommand_ConvertLF)
        self.button_SendNewCommand = QtWidgets.QPushButton(self.tab_2)
        self.button_SendNewCommand.setObjectName("button_SendNewCommand")
        self.verticalLayout_7.addWidget(self.button_SendNewCommand)
        self.tabWidget_ImapSession.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget_ImapSession)

        self.retranslateUi(SessionDialog)
        self.tabWidget_ImapSession.setCurrentIndex(0)
        self.tabWidget_Command.setCurrentIndex(0)
        self.tabWidget_Response.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SessionDialog)

    def retranslateUi(self, SessionDialog):
        _translate = QtCore.QCoreApplication.translate
        SessionDialog.setWindowTitle(_translate("SessionDialog", "Dialog"))
        self.label_2.setText(_translate("SessionDialog", "Server-Peer"))
        self.label.setText(_translate("SessionDialog", "Client-Peer"))
        self.label_3.setText(_translate("SessionDialog", "Current State"))
        self.cb_intercepted.setText(_translate("SessionDialog", "Intercepted"))
        self.tabWidget_Command.setTabText(self.tabWidget_Command.indexOf(self.tab_3), _translate("SessionDialog", "Raw"))
        self.treeWidget_CommandTree.headerItem().setText(0, _translate("SessionDialog", "Rule"))
        self.treeWidget_CommandTree.headerItem().setText(1, _translate("SessionDialog", "Data"))
        self.tabWidget_Command.setTabText(self.tabWidget_Command.indexOf(self.tab_4), _translate("SessionDialog", "Tree"))
        self.tabWidget_Response.setTabText(self.tabWidget_Response.indexOf(self.tab_5), _translate("SessionDialog", "Raw"))
        self.treeWidget_ResponseTree.headerItem().setText(0, _translate("SessionDialog", "Rule"))
        self.treeWidget_ResponseTree.headerItem().setText(1, _translate("SessionDialog", "Data"))
        self.tabWidget_Response.setTabText(self.tabWidget_Response.indexOf(self.tab_6), _translate("SessionDialog", "Tree"))
        self.tabWidget_ImapSession.setTabText(self.tabWidget_ImapSession.indexOf(self.tab), _translate("SessionDialog", "History"))
        self.checkBox_NewCommand_ConvertLF.setText(_translate("SessionDialog", "Convert \"\\n\" to \"\\r\\n\""))
        self.button_SendNewCommand.setText(_translate("SessionDialog", "Send Command"))
        self.tabWidget_ImapSession.setTabText(self.tabWidget_ImapSession.indexOf(self.tab_2), _translate("SessionDialog", "New Command"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SessionDialog = QtWidgets.QDialog()
    ui = Ui_SessionDialog()
    ui.setupUi(SessionDialog)
    SessionDialog.show()
    sys.exit(app.exec_())
